use dbms_proj;

SELECT FLIGHT.FLIGHT_CODE, COUNT(PASSENGER3.PID) AS TotalPassengers
FROM FLIGHT
LEFT JOIN PASSENGER3 ON FLIGHT.FLIGHT_CODE = PASSENGER3.FLIGHT_CODE
GROUP BY FLIGHT.FLIGHT_CODE;

SELECT FLIGHT.FLIGHT_CODE, FLIGHT.SOURCE, CITY.CNAME AS DepartureCity, CITY.COUNTRY AS DepartureCountry
FROM FLIGHT
INNER JOIN AIRPORT ON FLIGHT.SOURCE = AIRPORT.STATE
INNER JOIN CITY ON AIRPORT.CNAME = CITY.CNAME;

SELECT EMPLOYEE1.JOBTYPE, SUM(EMPLOYEE2.SALARY) AS TotalSalaryExpense
FROM EMPLOYEE1
INNER JOIN EMPLOYEE2 ON EMPLOYEE1.JOBTYPE = EMPLOYEE2.JOBTYPE
GROUP BY EMPLOYEE1.JOBTYPE;

SELECT PASSENGER1.PASSPORTNO, PASSENGER2.FNAME || ' ' || PASSENGER2.LNAME AS FullName, PASSENGER3.FLIGHT_CODE
FROM PASSENGER3
INNER JOIN PASSENGER1 ON PASSENGER3.PID = PASSENGER1.PID
INNER JOIN PASSENGER2 ON PASSENGER1.PASSPORTNO = PASSENGER2.PASSPORTNO;

SELECT SUM(TO_NUMBER(SUBSTR(DURATION, 1, 2))) AS TotalHours, SUM(TO_NUMBER(SUBSTR(DURATION, 4, 2))) AS TotalMinutes
FROM FLIGHT;

SELECT COUNT(*)
FROM TICKET1
WHERE SOURCE = 'BOM';

SELECT A.CNAME, COUNT(*)
FROM AIRPORT A
JOIN FLIGHT F ON A.AP_NAME = F.SOURCE
GROUP BY A.CNAME;

SELECT E2.JOBTYPE, AVG(E1.SALARY) AS avg_salary
FROM EMPLOYEE1 E1
JOIN EMPLOYEE2 E2 ON E1.JOBTYPE = E2.JOBTYPE
GROUP BY E2.JOBTYPE;

SELECT COUNT(*)
FROM PASSENGER3 P3
WHERE P3.FLIGHT_CODE IN (SELECT FLIGHT_CODE FROM FLIGHT WHERE AIRLINEID = 'AA');

SELECT P2.FNAME, P2.LNAME
FROM PASSENGER1 P1
JOIN PASSENGER2 P2 ON P1.PID = P2.PID
JOIN TICKET1 T ON P1.PID = T.PID AND P1.PASSPORTNO = T.PASSPORTNO
JOIN FLIGHT F ON T.SOURCE = F.SOURCE
JOIN AIRPORT A ON F.SOURCE = A.AP_NAME
WHERE A.COUNTRY = 'India';

SELECT (SELECT COUNT(*) FROM PASSENGER3 WHERE FLIGHT_CODE IN (SELECT FLIGHT_CODE FROM FLIGHT WHERE SOURCE = 'DFW')) -
(SELECT COUNT(*) FROM PASSENGER3 WHERE FLIGHT_CODE IN (SELECT FLIGHT_CODE FROM FLIGHT WHERE SOURCE = 'JFK')) AS PassengerDifference;

SELECT (COUNT(CASE WHEN F.STATUS = 'On-time' THEN 1 END) / COUNT(*)) * 100 AS OnTimePercentage
FROM FLIGHT F;
